### ISSUE TITLE
Conflict with Yoast SEO 9.3 on Wordpress 5.0.2 

### ISSUE THREAD

**Issue by BamaStangGuy** [understrap/understrap-child#204] opened 2018-12-20 23:18 UTC
Hello,

When using Wordpress 5.0.2 and Yoast SEO 9.3, click the edit link on any page breaks (only a white page is shown)  with the following Chrome Console javascript error.
[1545347519020.log](https://github.com/understrap/understrap-child/files/2700945/1545347519020.log)
[1545347538221.log](https://github.com/understrap/understrap-child/files/2700946/1545347538221.log)

**Comment by BamaStangGuy** [comment] 2018-12-20 23:23
This issue is brought up here: https://github.com/Yoast/wordpress-seo/issues/11767 but the issue does not appear when keeping Yoast enabled and disabling Understrap in favor of TwentyNineteen

**Comment by 0dp** [comment] 2018-12-21 14:05
I havn't checked my self but understrap uses the default `edit_post_link`
https://codex.wordpress.org/Function_Reference/edit_post_link

How is TwentyNineteen implementing this differently?

**Comment by sera2007** [comment] 2019-01-11 13:01
Hi there
I'm using Impreza 5 theme, just updated WP -> 5.0.2 and got the same problem :((
The Visual Composer doesn't work, because of a lot of JS problems.

1) When I was trying to use the Gutenberg editor - it loads just a white page...
2) When the Classic editor was installed, again it doesn't work because of a lot of JS errors. 

I'm using Yoast SEO Premium 9.1

http://take.ms/TLtx1

**Comment by Thomas-A-Reinert** [comment] 2019-01-11 13:07
@sera2007 : From what I understand, Impreza is a commercial theme available on themeforest? If that's corrrect, I'd contact the theme author. You already payed for support.
You issue has nothing to do with understrap, I guess.

**Comment by axlright** [comment] 2019-01-11 17:41
I'm running WordPress 5.0.3 and Yoast 9.4 (regular, not premium) and UnderStrap 0.8.9 as well as UnderStrap Child 0.5.2 and I'm not experiencing the white screen of death when editing posts using Gutenberg. I'm getting a shitload of JS errors, but those errors persist even when using the stock Twentynineteen 1.2.

I'm happy to try to help troubleshoot but I can confirm that the most recent version of WordPress + UnderStrap + UnderStrap Child + Yoast are all working together fine for me.

**Comment by Thomas-A-Reinert** [comment] 2019-07-11 01:33
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.

**Closed by Thomas-A-Reinert** 2019-07-11 01:33 UTC
