### ISSUE TITLE
Can't reference sass variables from src/sass/bootstrap4/_variables.scss in sass/theme/_child_theme_variables.scss ?

### ISSUE THREAD

**Issue by bongoman** [understrap/understrap-child#187] opened 2018-09-06 00:53 UTC
For example, in sass/theme/_child_theme_variables.scss I have:

`$primary:       $red !default;`

But gulp returns error:

`Undefined variable: "$red"`

**Comment by axlright** [comment] 2018-09-27 15:18
This is happening because the sass variable `$red` isn't defined until `src/sass/bootstrap4/_variables.scss` which is loaded after `sass/theme/_child_theme_variables.scss` according to the order of sass files in `sass/child_theme.scss`

You're referencing a variable that doesn't exist yet.

`sass/theme/_child_theme_variables.scss` is a place to set or change variables, but referencing a stock / default Bootstrap variable that isn't declared yet will break the compiler. To accomplish your stated goal, use:

```
$red: #dc3545;
$primary: $red;
```
Closing this issue because it doesn't relate directly to the understrap_child theme and rather is a question about Sass compiling. Feel free to comment is you feel the issue is unresolved and does apply to the understrap_child theme.

**Closed by axlright** 2018-09-27 15:18 UTC
