### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by mind-ctrl-spider** [understrap/understrap-child#231] opened 2019-06-05 00:50 UTC
I have gulp and browser-sync installed globally. When I try to npm install locally, it complains about missing files and fails. This is the output "right out of the box."

`vagrant@vvv:/srv/www/thefridacinema/public_html/wp-content/themes/understrap-child-master$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: file-type@4.4.0 (node_modules/archive-type/node_modules/file-type):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/srv/www/thefridacinema/public_html/wp-content/themes/understrap-child-master/node_modules/archive-type/node_modules/file-type/package.json.2898820522'

npm ERR! path /srv/www/thefridacinema/public_html/wp-content/themes/understrap-child-master/node_modules/array-initial/node_modules/is-number/package.json.3824351207
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/srv/www/thefridacinema/public_html/wp-content/themes/understrap-child-master/node_modules/array-initial/node_modules/is-number/package.json.3824351207'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
`
I have tried deleting node_modules and package-lock.json -- with similar results: complaints about missing files, then fails. What am I doing wrong?

**Comment by 0dp** [comment] 2019-06-05 12:07
What version of node and npm are you running?

**Comment by mind-ctrl-spider** [comment] 2019-06-05 12:43
node v11.15.0
npm v6.9.0

vvv v3.0.0
gulp-cli v2.2.0

**Comment by mind-ctrl-spider** [comment] 2019-06-05 13:04
It is always a non-existent package.json.####

**Comment by 0dp** [comment] 2019-06-05 16:56
Is it consistent what packages it fails on, or seemlessly random

**Comment by mind-ctrl-spider** [comment] 2019-06-05 18:04
If I try npm install again, it will fail on a different package... and so on...

**Comment by 0dp** [comment] 2019-06-05 19:32
node v10.16.0
npm v6.9.0

I had no issues trying to install, so lets proceed troubleshooting your local setup.

try to remove the node_modules folder.
Then execute `npm cache clean` then `npm install`

Also for good measurements, make sure your user have write permissions to the dir

**Comment by mind-ctrl-spider** [comment] 2019-06-05 19:48
I have cleaned the cache, removed node_modules. I spent all day on this yesterday. I think it might be my version of nodejs (11.15.0), which comes with VVV.

I installed nodejs 10.16.0 globally on Windows (not a VM) and had absolutely no problems at all.

**Comment by 0dp** [comment] 2019-06-05 20:28
current stable is 10.16.0 give it a shot with downgrading and lets see if it works :)

**Comment by mind-ctrl-spider** [comment] 2019-06-05 21:04
not quite sure how to downgrade nodejs version in the vm.

**Comment by Thomas-A-Reinert** [comment] 2019-06-05 23:17
Uninstall, reinstall to recommended version should do the job.  Please keep us up to date ..

**Comment by mind-ctrl-spider** [comment] 2019-06-06 00:31
I can't figure out how to downgrade without screwing everything up.

**Comment by 0dp** [comment] 2019-06-06 05:51
What OS is your VM?

**Comment by mind-ctrl-spider** [comment] 2019-06-06 17:23
VVV 3 runs Ubuntu 18. I'm having trouble uninstalling node 11, then getting the version we want (10).

**Comment by 0dp** [comment] 2019-06-08 11:28
This guide has the steps to install LTS version of node on Ubuntu.

https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/

.
To uninstall current version, assuming you used apt to install, do something like:

`sudo apt-get remove nodejs`

**Comment by mind-ctrl-spider** [comment] 2019-06-08 16:47
I see what is happening now. A fresh VVV install comes with nodejs 10.16.0, but any time I provision, it updates nodejs to 11.15.0, so I will have to figure out how to prevent that particular update during provisioning.

**Comment by 0dp** [comment] 2019-06-10 09:54
I'm not an expert on vagrant.

But maybe take a look at provision.sh and see if node is being updated.

It's an old thread but might be relevant for you:

https://github.com/Varying-Vagrant-Vagrants/VVV/issues/952

**Comment by KenEucker** [comment] 2019-06-11 06:50
Interesting, I am running into this issue on my linux environment now after things we working without issue for the last 2 months. Using npm v6.9.0 (previously 6.7.0) and node version 11.10. This issue also exists with yarn install.

However, it's failing on another file, in the copy-assets gulp task that runs on postinstall.

> Error: File not found with singular glob:/themes/mytheme/node_modules/understrap/node_modules/undescores-for-npm/js/skip-link-focus-fix.js (if this was purposeful, use `allowEmpty` option)

It seems as though there is an error occurring with node_module folder within the npm package.

**Comment by 0dp** [comment] 2019-06-11 07:10
Hey @KenEucker,

I can help but notice you've installed understrap as a dependency of understrap with npm.

So your error is something else.

You can try and remove understrap from your node_modules folder and see if that fixes things.

**Comment by KenEucker** [comment] 2019-06-11 07:20
@0dp https://github.com/understrap/understrap-child/blob/master/package.json#L52

**Comment by KenEucker** [comment] 2019-06-11 07:51
@0dp 

My issues with running `npm install` were resolved by removing the dependency found on line 52 of package.json: https://github.com/understrap/understrap-child/blob/master/package.json#L52

In looking through the history of this file, it seems that understrap has been a dependency since the first commit.

**Comment by mind-ctrl-spider** [comment] 2019-06-15 22:15
I found in provision.sh where VVV was upgrading to Node 11.x and changed it to 10.x, then started from scratch.
Still had the missing package.js when trying to run a project-local `npm install`
So I cheated. I'm copied the `node_modules` folder from my local in my project-local install on Bitnami WAMP into my VVV project-local folder.
I had to run npm rebuild node-sass, but now it works great!

**Comment by 0dp** [comment] 2019-06-16 07:44
@KenEucker, i am not sure why understrap is a dependency of itself. But it seems unnecessary to me. So removing it should be fine.
Come to think of it, it could create more bad than good.

@mind-ctrl-spider
Great you found out how to prevent the update.
Is the missing package problems exactly the same?

Have you tried making a new empty project `npm init` and try to install some arbitrary packages?
Maybe the problem is not related to understrap nor mom, but server/network related.

**Comment by mind-ctrl-spider** [comment] 2019-06-16 19:14
> Is the missing package problems exactly the same?

Yes. Same problem. I haven't tried individually yet. I'll start fresh and give it a go when I have a moment or twelve.

**Comment by mansouryaacoubi** [comment] 2019-08-14 11:46
Seems to be failing at multiple points. .Net Framework is installed and so is browsersync and gulp.

![image](https://user-images.githubusercontent.com/6348858/63018613-94f70080-be99-11e9-89cb-55c504667257.png)

![image](https://user-images.githubusercontent.com/6348858/63018693-ca035300-be99-11e9-82b6-79ce2fd1a67f.png)

**Comment by monkishtypist** [comment] 2019-11-07 16:49
This could be same same as #229 

There is an issue with how path variables are set in the `understrap` dependency cause `File not found` errors.

**Comment by 120dev** [comment] 2021-04-28 07:43
thats work for me : `rm -rf node_modules && npm install --cache /tmp/empty-cache`

**Closed** 2021-07-07 14:07 UTC
