### ISSUE TITLE
Custom JS file

### ISSUE THREAD

**Issue by 2021creative** [understrap/understrap-child#166] opened 2018-06-06 05:17 UTC
Absolutely loving this, thanks so much for all your hard work!

I have just updated the parent and child for a project where I'm using understrap and I came across a problem - the custom JS file wasn't being compiled into the child-theme.js and therefore not getting uglified into the .min.js either. I traced that to the gulpfile.js on lines 144~146 where there is this:

`// Adding currently empty javascript file to add on for your own themes´ customizations
// Please add any customizations to this .js file only!
paths.dev + '/js/custom-javascript.js'`

which is suggesting to put custom JavaScript functions etc in the src folder if I'm not mistaken? For me this is confusing and I thought they should be in the JS folder to match the location of the custom scss files. Simple enough to change, and I've done that by adding the following:

`// The above wasn't working for me so I'm referring to the 
// JS folder NOT in SRC and a custom.js file in there
paths.js + '/custom.js'`

but I was just wondering if this was a good idea? I suppose both the scss and js customisations are 'source' material in some ways, just a secondary source compared to base libraries that won't be edited...

Anyway I thought I'd mention it here and see what your thoughts were. Again, I can't say enough thanks for the amazing work putting this together and maintaining it all. It's an amazing tool and also a fantastic way to learn about task runners, scss and other elements of advanced workflows with WordPress!

**Comment by 2021creative** [comment] 2018-06-06 05:31
OK now I'm actually a little confused.... even the readme is suggesting to customise scss inside the sass folder, not the src/sass folder. And that is exactly what I've done, but then it follows in my mind that the JavaScript should work the same way? But I also see that there is structure for custom scss to go into the src folder! What should I do?!

**Comment by jwnip** [comment] 2018-10-31 14:12
I had the exact same thought.

Given the structure of the other custom files, I would expect the `custom-javascript.js` file to be placed in the `/understrap-child/js/` directory.

**Comment by ramojej** [comment] 2018-11-29 02:43
> OK now I'm actually a little confused.... even the readme is suggesting to customise scss inside the sass folder, not the src/sass folder. And that is exactly what I've done, but then it follows in my mind that the JavaScript should work the same way? But I also see that there is structure for custom scss to go into the src folder! What should I do?!

I'm having the same dilemma right now.

**Comment by nelitow** [comment] 2018-12-18 17:32
Should I place my js in /understrap-child/src/js/custom-javascript.js?
If yes, why it doesn't load when I run gulp watch or gulp scripts? What am I missing?
My gulpfile.js is stock
`gulp.task( 'scripts', function() {
    var scripts = [

        // Start - All BS4 stuff
        paths.dev + '/js/bootstrap4/bootstrap.js',

        // End - All BS4 stuff

        paths.dev + '/js/skip-link-focus-fix.js',

        // Adding currently empty javascript file to add on for your own themes´ customizations
        // Please add any customizations to this .js file only!
        paths.dev + '/js/custom-javascript.js'
    ];
  gulp.src( scripts )
    .pipe( concat( 'child-theme.min.js' ) )
    .pipe( uglify() )
    .pipe( gulp.dest( paths.js ) );

  gulp.src( scripts )
    .pipe( concat( 'child-theme.js' ) )
    .pipe( gulp.dest( paths.js ) );
});`

**Comment by 0dp** [comment] 2018-12-19 15:34
@nelitow have you tried something real simple like an alert or console.log just for troubleshooting causes?

It should work out of the box like that `gulp scripts` and `gulp watch-bs` / `gulp watch`

**Comment by nelitow** [comment] 2018-12-19 17:03
@0dp I did, no success. No cache enabled on the website either. Do you know of a tutorial, so I can follow along and see if I missed something?

**Comment by 0dp** [comment] 2018-12-19 21:36
I'm sorry I can't reproduce the error you are describing.

I just did a fresh install of the child-theme
ran npm install
created the custom-javascript.js file in /src/js
added a simple console log statement and ran `gulp scripts`
No problem at all.

Do you have any errors in your browser console?

**Comment by nelitow** [comment] 2018-12-20 00:19
It's working now and I really don't know why it wasn't before. But since you mentioned, I do get a

> /wp-content/themes/understrap/js/popper.min.js?ver=5.0.1 404 (Not Found)
Might be something wrong with my setup?
Appreciate the help already

**Comment by Waicung** [comment] 2019-04-08 05:29
Where the custom js file should locate: /understrap-child/src/js/custom-javascript.js
Reminder: if you have attempted to modify gulpfile.json, revert to the original version then run the 
`gulp scripts` and `gulp watch-bs` / `gulp watch`

**Comment by ramojej** [comment] 2019-04-29 12:00
> I'm sorry I can't reproduce the error you are describing.
> 
> I just did a fresh install of the child-theme
> ran npm install
> created the custom-javascript.js file in /src/js
> added a simple console log statement and ran `gulp scripts`
> No problem at all.
> 
> Do you have any errors in your browser console?

In the previous version of Understrap Child and also my previous project, I created custom.js and custom-slick.js. Added these files to the gulpfile.js and is working perfect. Now, though, it just won't work. It's being compiled to the child-theme.js, but not in the child-theme.min.js. Also, when I changed the directory of child-theme.min.js in the functions.php to be 'child-theme.js' only, my console.log won't also work, even though it's in the child-theme.js file. Weird.

**Comment by SaleebM** [comment] 2019-05-08 02:22
Had the same issue myself. 
Solution would be to add the proper trailing slash before js [here](https://github.com/understrap/understrap-child/blob/4573f1e88b4916b4f46ebc94b019cc718c01cd41/gulpfile.js#L134) as such:

``${paths.dev}/js/custom-javascript.js`,`

**Comment by markcorcoran** [comment] 2019-05-23 03:46
I just updated to new Understrap on a project and had the same issue. The custom-javascipt.js file was not compiling and drove me crazy. The solution above with missing / before JS was the issue in Gulp file. Important fix.

**Comment by Thomas-A-Reinert** [comment] 2019-07-11 01:33
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.

**Closed by Thomas-A-Reinert** 2019-07-11 01:33 UTC
